/* eslint-disable */
/**
 * Generated `api` utility.
 * THIS FILE IS AUTO-GENERATED BY `npx convex dev`.
 */
"use strict";

const { anyApi } = require("convex/server");

/**
 * A utility for referencing Convex functions in your app's API.
 */
const api = anyApi;
const internal = anyApi;

module.exports = { api, internal };
