/* eslint-disable */
/**
 * Generated `api` utility.
 * THIS FILE IS AUTO-GENERATED BY `npx convex dev`.
 * Run `npx convex dev` to regenerate.
 */

import type { ApiFromModules } from "convex/server";
import type * as auth from "../auth.js";
import type * as assets from "../assets.js";
import type * as seed from "../seed.js";

export declare const api: ApiFromModules<{
  auth: typeof auth;
  assets: typeof assets;
  seed: typeof seed;
}>;

export declare const internal: ApiFromModules<Record<string, never>>;
