/* eslint-disable */
/**
 * Generated server-side helpers.
 * THIS FILE IS AUTO-GENERATED BY `npx convex dev`.
 */

import type {
  GenericActionCtx,
  GenericMutationCtx,
  GenericQueryCtx,
  GenericDatabaseReader,
  GenericDatabaseWriter,
} from "convex/server";
import type { DataModel } from "./dataModel.js";

export type DatabaseReader = GenericDatabaseReader<DataModel>;
export type DatabaseWriter = GenericDatabaseWriter<DataModel>;
export type QueryCtx = GenericQueryCtx<DataModel>;
export type MutationCtx = GenericMutationCtx<DataModel>;
export type ActionCtx = GenericActionCtx<DataModel>;

export declare const query: import("convex/server").RegisteredQuery<"public", Record<string, never>, Promise<never>>;
export declare const mutation: import("convex/server").RegisteredMutation<"public", Record<string, never>, Promise<never>>;
export declare const action: import("convex/server").RegisteredAction<"public", Record<string, never>, Promise<never>>;
export declare const internalQuery: import("convex/server").RegisteredQuery<"internal", Record<string, never>, Promise<never>>;
export declare const internalMutation: import("convex/server").RegisteredMutation<"internal", Record<string, never>, Promise<never>>;
export declare const internalAction: import("convex/server").RegisteredAction<"internal", Record<string, never>, Promise<never>>;
