/* eslint-disable */
/**
 * Generated server-side helpers.
 * THIS FILE IS AUTO-GENERATED BY `npx convex dev`.
 */
"use strict";

const { queryGeneric, mutationGeneric, actionGeneric, internalQueryGeneric, internalMutationGeneric, internalActionGeneric } = require("convex/server");

const query = queryGeneric;
const mutation = mutationGeneric;
const action = actionGeneric;
const internalQuery = internalQueryGeneric;
const internalMutation = internalMutationGeneric;
const internalAction = internalActionGeneric;

module.exports = { query, mutation, action, internalQuery, internalMutation, internalAction };
